2 new Wallpaper
dominichayesferen/FerenMoefier pull request #4
Opened 2021-04-09 12:10 UTC by Nikurasukun

I added 2 more wallpaper for more moe. The huge changes in the Moeification.pot are there because I opend the file in Poedit and saved it.

2021-04-10 19:35 UTC, dominichayesferen requested changes
There's only one breakage that means I'm gonna have to mark this as NEEDS CHANGES, but this is otherwise a GREAT first merge request, well done!

I'll probably end up regenerating the .pot in case again after merge anyway, so... yeah, dw, hopefully it still works.

2021-04-10 19:35 UTC, dominichayesferen commented on Moeification.sh
> +wget https://teddit.net/pics/w:null_35a1utot7vh61.png -O "/usr/share/weebpapers/(Moe) Ai Ohto.png" > /dev/null 2>&1
The link died.

2021-04-10 19:35 UTC, dominichayesferen commented on Moeification.sh
> +    echo "$(eval_gettext "Oh no, an error occured downloading the Yoimoi wallpaper, the girls will never reach antarctica!") $(eval_gettext "Aborting now.")"
Just FYI I'd do this myself post-merge, but... I'd personally change 'antarctica' to 'Antarctica', and change it from 'wallpaper, the' to 'wallpaper. The'.

2021-05-07 17:59 UTC, Nikurasukun commented
So, I fixed the Links and the Typos now. Sorry for not replying for so long, I had much things to do like my finals. Now I finally found time to fix all the things you mentioned. :-)

2021-05-08 12:01 UTC, dominichayesferen commented
seems 👌🏻 now, so...

2021-05-08 12:01 UTC, merged